# Generated by Django 5.0.4 on 2024-04-26 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adresse',
            fields=[
                ('id_adresse', models.AutoField(primary_key=True, serialize=False)),
                ('rue', models.CharField(max_length=50)),
                ('num_rue', models.IntegerField()),
                ('ville', models.CharField(max_length=50)),
                ('code_postal', models.IntegerField()),
                ('pays', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id_equipe', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Stade',
            fields=[
                ('id_stade', models.AutoField(primary_key=True, serialize=False)),
                ('nom_stade', models.CharField(max_length=50)),
                ('capacite', models.IntegerField()),
                ('adresse', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='supporters.adresse')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id_match', models.AutoField(primary_key=True, serialize=False)),
                ('date_match', models.DateTimeField()),
                ('equipe_away', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipe_away_id', to='supporters.equipe')),
                ('equipe_home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipe_home_id', to='supporters.equipe')),
                ('stade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supporters.stade')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id_ticket', models.AutoField(primary_key=True, serialize=False)),
                ('type_ticket', models.CharField(max_length=50)),
                ('emplacement', models.CharField(max_length=50)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supporters.game')),
            ],
        ),
        migrations.CreateModel(
            name='Supporter',
            fields=[
                ('id_supporter', models.AutoField(primary_key=True, serialize=False)),
                ('cin', models.IntegerField()),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('date_naissance', models.DateField()),
                ('sexe', models.CharField(max_length=50)),
                ('acces', models.CharField(max_length=50)),
                ('adresse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supporters.adresse')),
                ('stade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supporters.stade')),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='supporters.ticket')),
            ],
        ),
    ]
