# Generated by Django 5.0.4 on 2024-04-26 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supporters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Zone', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
    ]
