# Generated by Django 5.0.4 on 2024-04-26 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supporters', '0003_delete_acces_remove_supporter_acces'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acces',
            fields=[
                ('id_acces', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
    ]
