# Generated by Django 5.0.4 on 2024-04-26 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supporters', '0004_acces'),
    ]

    operations = [
        migrations.RenameField(
            model_name='acces',
            old_name='nom',
            new_name='zone_acces',
        ),
        migrations.AddField(
            model_name='supporter',
            name='acces',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='supporters.acces'),
        ),
        migrations.AlterField(
            model_name='acces',
            name='description',
            field=models.TextField(),
        ),
    ]
